version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=sqlite:///data/users.db
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - SEED_DEFAULT_ADMIN=true
      - FRONTEND_URL=http://172.105.53.187:3000
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://172.105.53.187:5000/api
    depends_on:
      - backend
